_           quit                          # File > Exit
Esc         cycle fullscreen              # Window > Fullscreen
_           quit-watch-later              # Tools > Exit Watch Later
_           quit                          # Exit
_           quit                          # Exit
